---
# tasks file for start_app
- name: install myapp as systemd service
  template: src=myapp.service.j2 dest=/etc/systemd/system/myapp.service
  
- name: install the bash script to start app
  template: src=webapp-start.sh.j2 dest=/home/vagrant/webapp-start.sh mode=0777

- name: Start my app
  systemd: state=started name=myapp enabled=yes daemon_reload=yes
